/**
 * Generates the repeating header for Puppeteer
 */
exports.getHeaderTemplate = (storeName, username, role, generationDate) => `
  <div style="font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; width: 100%; padding: 0 40px; margin-top: 20px;">
    <div style="display: flex; align-items: center; margin-bottom: 10px;">
      <div style="width: 60px; height: 60px; background-color: #ddd; margin-right: 15px; display: flex; align-items: center; justify-content: center; font-size: 10px; color: #666;">
        [LOGO]
      </div>
      <div>
        <h1 style="margin: 0; font-size: 22px; color: #000; font-weight: bold;">Sell, Observe, Restock (SOBRE)</h1>
        <p style="margin: 2px 0; font-size: 10px; color: #000;"><b>Generated For:</b> ${storeName}</p>
        <p style="margin: 2px 0; font-size: 10px; color: #000;"><b>Generated By:</b> ${username} (${role})</p>
        <p style="margin: 2px 0; font-size: 10px; color: #000;"><b>Date and Time:</b> ${generationDate}</p>
      </div>
    </div>
    <div style="border-bottom: 2px solid #004385; width: 100%;"></div>
  </div>
`;

/**
 * Generates the repeating footer for Puppeteer
 */
exports.getFooterTemplate = () => `
  <div style="font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; width: 100%; padding: 0 40px; text-align: right; font-size: 10px; color: #000;">
    Page <span class="pageNumber"></span>
  </div>
`;

/**
 * Wraps the specific report tables and summaries in the base Tailwind HTML shell
 */
exports.buildReportHTML = (reportTitle, tableHeadersHTML, tableRowsHTML, summaryHTML) => `
  <!DOCTYPE html>
  <html>
  <head>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
      table { page-break-inside: auto; }
      tr { page-break-inside: avoid; page-break-after: auto; }
      .summary-container { page-break-inside: avoid; }
    </style>
  </head>
  <body class="font-sans text-black text-[10px] m-0">
    
    <h2 class="text-center text-base font-bold mb-5 mt-2">${reportTitle}</h2>
    
    <table class="w-full border-collapse">
      <thead>
        <tr>
          ${tableHeadersHTML}
        </tr>
      </thead>
      <tbody>
        ${tableRowsHTML}
      </tbody>
    </table>

    <div class="summary-container mt-10">
      <div class="text-sm font-bold mb-4">Summary:</div>
      ${summaryHTML}
    </div>

  </body>
  </html>
`;